# Challenge
## **Context**

These are all the flights tracked by the National Civil Aviation Agency, in Brazil, from January 2015 to August 2017.

## **Content**

The dataset is in portuguese so I had to remove some characters that were not supported on Kaggle. You can see the translation for the columns in the main dataset description.

"Nao Identificado" means "Unidentified".

UF means the State where the airport is located. For every airport not located in Brazil, the value is N/I.

Link: https://www.kaggle.com/ramirobentes/flights-in-brazil

# 1- Carregar as Bibliotecas

> Numpy, pandas, plotly, matplotlib...

In [1]:
import pandas as pd

,Voos,Companhia.Aerea,Codigo.Tipo.Linha,Partida.Prevista,Partida.Real,Chegada.Prevista,Chegada.Real,Situacao.Voo,Codigo.Justificativa,Aeroporto.Origem,...,Estado.Origem,Pais.Origem,Aeroporto.Destino,Cidade.Destino,Estado.Destino,Pais.Destino,LongDest,LatDest,LongOrig,LatOrig
0,AAL - 203,AMERICAN AIRLINES INC,Internacional,2016-01-30T08:58:00Z,2016-01-30T08:58:00Z,2016-01-30T10:35:00Z,2016-01-30T10:35:00Z,Realizado,NaN,Afonso Pena,...,PR,Brasil,Salgado Filho,Porto Alegre,RS,Brasil,-51.175381,-29.993473,-49.172481,-25.532713
1,AAL - 203,AMERICAN AIRLINES INC,Internacional,2016-01-13T12:13:00Z,2016-01-13T12:13:00Z,2016-01-13T21:30:00Z,2016-01-13T21:30:00Z,Realizado,NaN,Salgado Filho,...,RS,Brasil,Miami,Miami,N/I,Estados Unidos,-80.287046,25.795865,-51.175381,-29.993473
2,AAL - 203,AMERICAN AIRLINES INC,Internacional,2016-01-29T12:13:00Z,2016-01-29T12:13:00Z,2016-01-29T21:30:00Z,2016-01-29T21:30:00Z,Realizado,NaN,Salgado Filho,...,RS,Brasil,Miami,Miami,N/I,Estados Unidos,-80.287046,25.795865,-51.175381,-29.993473
3,AAL - 203,AMERICAN AIRLINES INC,Internacional,2016-01-19T12:13:00Z,2016-01-18T12:03:00Z,2016-01-19T21:30:00Z,2016-01-18T20:41:00Z,Realizado,LIBERACAO SERV. TRAFEGO AEREO/ANTECIPACAO,Salgado Filho,...,RS,Brasil,Miami,Miami,N/I,Estados Unidos,-80.287046,25.795865,-51.175381,-29.993473
4,AAL - 203,AMERICAN AIRLINES INC,Internacional,2016-01-30T12:13:00Z,2016-01-30T12:13:00Z,2016-01-30T21:30:00Z,2016-01-30T21:30:00Z,Realizado,NaN,Salgado Filho,...,RS,Brasil,Miami,Miami,N/I,Estados Unidos,-80.287046,25.795865,-51.175381,-29.993473

In [8]:
pd.get_dummies(db, columns=['Companhia.Aerea'])

,Voos,Codigo.Tipo.Linha,Partida.Prevista,Partida.Real,Chegada.Prevista,Chegada.Real,Situacao.Voo,Codigo.Justificativa,Aeroporto.Origem,Cidade.Origem,...,Companhia.Aerea_TAAG LINHAS AEREAS DE ANGOLA,Companhia.Aerea_TAM,Companhia.Aerea_TAM TRANSP. AR. DEL. MERCOS,Companhia.Aerea_TAP AIR PORTUGAL,Companhia.Aerea_TOTAL,Companhia.Aerea_TRASAMERICA AIRLINES-TACAPERU,Companhia.Aerea_TRIP,Companhia.Aerea_TURKISH AIRLINES INC.,Companhia.Aerea_UNITED AIRLINES,Companhia.Aerea_US AIRWAYS INC.
0,AAL - 203,Internacional,2016-01-30T08:58:00Z,2016-01-30T08:58:00Z,2016-01-30T10:35:00Z,2016-01-30T10:35:00Z,Realizado,NaN,Afonso Pena,Sao Jose Dos Pinhais,...,0,0,0,0,0,0,0,0,0,0
1,AAL - 203,Internacional,2016-01-13T12:13:00Z,2016-01-13T12:13:00Z,2016-01-13T21:30:00Z,2016-01-13T21:30:00Z,Realizado,NaN,Salgado Filho,Porto Alegre,...,0,0,0,0,0,0,0,0,0,0
2,AAL - 203,Internacional,2016-01-29T12:13:00Z,2016-01-29T12:13:00Z,2016-01-29T21:30:00Z,2016-01-29T21:30:00Z,Realizado,NaN,Salgado Filho,Porto Alegre,...,0,0,0,0,0,0,0,0,0,0
3,AAL - 203,Internacional,2016-01-19T12:13:00Z,2016-01-18T12:03:00Z,2016-01-19T21:30:00Z,2016-01-18T20:41:00Z,Realizado,LIBERACAO SERV. TRAFEGO AEREO/ANTECIPACAO,Salgado Filho,Porto Alegre,...,0,0,0,0,0,0,0,0,0,0
4,AAL - 203,Internacional,2016-01-30T12:13:00Z,2016-01-30T12:13:00Z,2016-01-30T21:30:00Z,2016-01-30T21:30:00Z,Realizado,NaN,Salgado Filho,Porto Alegre,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2542514,UAL - 129,Internacional,2015-12-14T01:25:00Z,2015-12-14T04:31:00Z,2015-12-14T11:19:00Z,2015-12-14T14:18:00Z,Realizado,ATRASOS NAO ESPECIFICOS - OUTROS,Houston,Houston,...,0,0,0,0,0,0,0,0,1,0
2542515,UAL - 129,Internacional,2015-12-01T01:25:00Z,2015-12-01T01:25:00Z,2015-12-01T11:19:00Z,2015-12-01T11:19:00Z,Realizado,NaN,Houston,Houston,...,0,0,0,0,0,0,0,0,1,0
2542516,UAL - 129,Internacional,2015-12-27T01:25:00Z,2015-12-27T01:25:00Z,2015-12-27T11:19:00Z,2015-12-27T11:19:00Z,Realizado,NaN,Houston,Houston,...,0,0,0,0,0,0,0,0,1,0
2542517,UAL - 129,Internacional,2015-12-05T01:25:00Z,2015-12-05T01:21:00Z,2015-12-05T11:19:00Z,2015-12-05T10:48:00Z,Realizado,ATRASOS NAO ESPECIFICOS - OUTROS,Houston,Houston,...,0,0,0,0,0,0,0,0,1,0
2542518,UAL - 129,Internacional,2015-12-09T01:25:00Z,2015-12-09T01:25:00Z,2015-12-09T11:19:00Z,2015-12-09T11:19:00Z,Realizado,NaN,Houston,Houston,...,0,0,0,0,0,0,0,0,1,0

In [11]:
db.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2542519 entries, 0 to 2542518
Data columns (total 21 columns):
 #   Column                Dtype
---  ------                -----
 0   Voos                  object
 1   Companhia.Aerea       object
 2   Codigo.Tipo.Linha     object
 3   Partida.Prevista      object
 4   Partida.Real          object
 5   Chegada.Prevista      object
 6   Chegada.Real          object
 7   Situacao.Voo          object
 8   Codigo.Justificativa  object
 9   Aeroporto.Origem      object
 10  Cidade.Origem         object
 11  Estado.Origem         object
 12  Pais.Origem           object
 13  Aeroporto.Destino     object
 14  Cidade.Destino        object
 15  Estado.Destino        object
 16  Pais.Destino          object
 17  LongDest              float64
 18  LatDest               float64
 19  LongOrig              float64
 20  LatOrig               float64
dtypes: float64(4), object(17)
memory usage: 407.4+ MB

# 2- Verificar e Interpretar as variÃ¡veis

> Head, dtypes, describe...

<br>
<center>
<img src="https://media1.tenor.com/images/e4848131a1af20a7e1de5e0443afe472/tenor.gif?itemid=4960555" alt="drawing" width="500px"></center>

# 3- Definir a HipÃ³tese

![Explo](../img/what-if.jpg "Variables specification")

# 4- Corrigir os ruÃ­dos e Organizar o Dataset

> Drop, fillna, NumericalFeaturesImputer...

<br>
<center>
<img src="http://media.tumblr.com/tumblr_medmv9n8JL1ro2d43.gif" alt="drawing" width="500px"></center>

# 5- Avaliar a HipÃ³tese

> GrÃ¡ficos ou testes de hipÃ³teses

<br>
<center>
<img src="https://media1.tenor.com/images/c109257362ef9924a11c64fd1b051f43/tenor.gif?itemid=5205898" alt="drawing" width="500px"></center>

# 6- Preparar e Apresentar os Resultados

<br>
<center>
<img src="https://i.imgur.com/CKyA2sd.gif" alt="drawing" width="500px"></center>